### PR TITLE
Fix method invalidations

### LINKED ISSUE #147: Significant method invalidations for `in` with Julia 1.11
I'm seeing the following SnoopCompile output:
```julia
 inserting in(inds::Dictionaries.ReverseIndices{I, Inds} where Inds<:Dictionaries.AbstractIndices{I}, i::I) where I @ Dictionaries ~/.julia/packages/Dictionaries/RaTRN/src/reverse.jl:7 invalidated:
   backedges:  1: superseding in(x, s::Set) @ Base set.jl:92 with MethodInstance for in(::Any, ::Set{T} where T<:Integer) (1 children)
               3: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::NTuple{5, Symbol}) (1 children)
               4: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Tuple{String, String, String, Nothing}) (1 children)
               5: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::NTuple{8, Symbol}) (1 children)
               6: superseding in(x, itr) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Array{String}) (1 children)
               7: superseding in(x, itr) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Base.Generator{I, DataFrames.var"#941#943"} where I<:(Base.Iterators.Filter{DataFrames.var"#942#944"})) (1 children)
              10: superseding in(k, v::Base.KeySet{<:Any, <:IdDict}) @ Base iddict.jl:182 with MethodInstance for in(::Any, ::Base.KeySet{Any, IdDict{Any, Nothing}}) (2 children)
              11: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Tuple{String, String, String}) (2 children)
              12: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Tuple{}) (2 children)
              13: superseding in(x, itr) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Vector{Any}) (2 children)
              14: superseding in(x, s::Set) @ Base set.jl:92 with MethodInstance for in(::Any, ::Set{<:Union{Missing, Integer}}) (3 children)
              15: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Tuple{Symbol, Symbol, Symbol}) (3 children)
              17: superseding in(key, v::Base.KeySet{<:Any, <:Dict}) @ Base dict.jl:549 with MethodInstance for in(::Any, ::Base.KeySet{String, Dict{String, Tuple{Any, Any}}}) (4 children)
              18: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Tuple{Symbol, Symbol}) (5 children)
              19: superseding in(x, itr) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::String) (7 children)
              20: superseding in(x, s::Set) @ Base set.jl:92 with MethodInstance for in(::Any, ::Set) (11 children)
              21: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Tuple{typeof(+), typeof(*)}) (13 children)
              22: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Tuple{Nothing, Bool}) (15 children)
              23: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Tuple{String, String}) (19 children)
              24: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Tuple{typeof(*), typeof(^)}) (20 children)
              25: superseding in(x, itr) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::BitSet) (26 children)
              26: superseding in(x, s::Set) @ Base set.jl:92 with MethodInstance for in(::Any, ::Set{Symbol}) (31 children)
              27: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Tuple{typeof(+), typeof(*), typeof(^)}) (31 children)
              28: superseding in(x, s::IdSet) @ Base idset.jl:44 with MethodInstance for in(::Any, ::IdSet{Dict}) (41 children)
              29: superseding in(x, s::Set) @ Base set.jl:92 with MethodInstance for in(::Any, ::Set{Any}) (63 children)
              30: superseding in(x, itr) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Vector) (78 children)
              31: superseding in(x, itr) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Vector{Symbol}) (109 children)
              32: superseding in(x, s::IdSet) @ Base idset.jl:44 with MethodInstance for in(::Any, ::IdSet{Dict{String}}) (114 children)
              33: superseding in(k, v::Base.KeySet{<:Any, <:IdDict}) @ Base iddict.jl:182 with MethodInstance for in(::Any, ::Base.KeySet{Any, IdDict{Any, Any}}) (481 children)
```
Some lines removed. The last few seem particularly concerning.

### PR DESCRIPTION
**Pull request by lkdvos**
This is a PR to attempt to fix #147

The invalidating code is indeed the definition of `in` for the reverse indices, and I tried digging around to find out what this method is supposed to do, but I got lost a bit.

From what I understand, `Base.in(item, collection)` is usually defined with untyped `item`, specializing on the collection.
However, here there is a specific implementation for `Base.in(item::ReverseIndices, collection::AbstractIndices)`, and I'm actually failing to see what this method is supposed to accomplish.
Somehow, this is mapping to a function where `in(item::I, collection::I)` is the result, so the item is of the same type as the collection, where I would have expected the item to be of the `eltype` of the collection.
I might be fully missing something here, but is it possible this is just some legacy thing that is never actually being called?

In any case, simply removing this method fixes all invalidations while still letting the tests pass.
In particular, I noted that `Base.in(item, inds::ReverseIndices)` definitely already works because it subtypes `AbstractIndices` and implements the required methods.
Otherwise, if you could maybe explain to me what I'm missing I'm more than happy to add some tests to capture this as well, and I'll try come up with a different attempt of fixing #147.

<details>
<summary>Current master + julia 1.11</summary>

```julia
using SnoopCompileCore
invs = @snoop_invalidations using Dictionaries
using SnoopCompile

julia> trees = invalidation_trees(invs)
1-element Vector{SnoopCompile.MethodInvalidations}:
 inserting in(inds::ReverseIndices{I, Inds} where Inds<:AbstractIndices{I}, i::I) where I @ Dictionaries ~/Projects/BugFixes/CatCompilation/dev/Dictionaries/src/reverse.jl:7 invalidated:
   backedges:  1: superseding in(key, v::Base.KeySet{<:Any, <:Dict}) @ Base dict.jl:549 with MethodInstance for in(::Any, ::Base.KeySet{String, Dict{String, Set{Any}}}) (1 children)
               2: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Tuple{Symbol, Symbol}) (1 children)
               3: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::NTuple{5, Symbol}) (1 children)
               4: superseding in(x, itr) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::String) (1 children)
               5: superseding in(x, s::Set) @ Base set.jl:92 with MethodInstance for in(::Any, ::Set{Base.PkgId}) (2 children)
               6: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::NTuple{6, Char}) (2 children)
               7: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Tuple{String, String, String}) (2 children)
               8: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::NTuple{11, Char}) (5 children)
               9: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Tuple{Char, Char, Char}) (5 children)
              10: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Tuple{Char, Char}) (7 children)
              11: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::NTuple{4, Char}) (14 children)
              12: superseding in(x, itr) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Vector{String}) (17 children)
              13: superseding in(x, itr::Tuple) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::Tuple{Nothing, Bool}) (20 children)
              14: superseding in(x, itr) @ Base operators.jl:1302 with MethodInstance for in(::Any, ::BitSet) (64 children)
              15: superseding in(k, v::Base.KeySet{<:Any, <:IdDict}) @ Base iddict.jl:182 with MethodInstance for in(::Any, ::Base.KeySet{Any, IdDict{Any, Any}}) (115 children)
   5 mt_cache
```

</details>

<details>
<summary>After PR + Julia 1.11</summary>

```julia
using SnoopCompileCore
invs = @snoop_invalidations using Dictionaries
using SnoopCompile
julia> trees = invalidation_trees(invs)
SnoopCompile.MethodInvalidations}[]
```

</details>

### CODE REVIEW

**Comment by theogf** [comment]
I guess we can still merge this despite the job failing.

**Review by theogf — APPROVED** [review]

**Comment by lkdvos** [comment]
That would be great, thanks!

File: src/reverse.jl [hunk 1]
```diff
@@ -4,7 +4,6 @@ struct ReverseIndices{I, Inds <: AbstractIndices{I}} <: AbstractIndices{I}
 end
 
 Base.parent(inds::ReverseIndices) = getfield(inds, :inds)
-@propagate_inbounds Base.in(inds::ReverseIndices{I}, i::I) where {I} = in(parent(inds), i)
```
Comment (andyferris) [inline src/reverse.jl:7]: Can we instead change the line to this?

```julia
@propagate_inbounds Base.in(inds::ReverseIndices) = in(parent(inds), i)
```

**Review by andyferris — CHANGES_REQUESTED** [review]
Thanks @lkdvos for the contribution - sorry I tried to get to this the other day and couldn't find a moment.

Currently `in` is required to be defined on containers that are not tokenizable. For tokenizable ones, the fallback `in` definition should be perfectly OK. But in the (admittedly academic) case that we are wrapping a non-tokenizable indices, there will be no functioning fallback.

Since `convert` shouldn't change the behavior `isequal`, we actually don't need these `::I` annotations for non-mutating methods. Does the change I propose fix the invalidations and work correctly?

File: src/reverse.jl (hunk 1 above)
Comment (lkdvos) [reply src/reverse.jl:7]: I'll try this out and let you know. Is it possible you are missing an argument in the function signature though?

**Comment by lkdvos** [comment]
Trying out the new approach still results in the same invalidations.
I just want to double check, you are sure you are looking for
```julia
@propagate_inbounds Base.in(inds::ReverseIndices, i) = in(parent(inds), i)
```
and not this
```julia
@propagate_inbounds Base.in(item, inds::ReverseIndices) = in(item, parent(inds))
```

The latter solves the invalidations, and seems to me like it is what we want anyways, but again, I might be missing something

**Comment by andyferris** [comment]
Oh haha - yes sorry about that, you are right!
